"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getById(1);
var newP = new Product_1.Product();
newP.name = 'iphone';
newP.category = 'phone';
newP.price = 10;
// _productService.saveProduct(newP);
_productService.deleteProduct(result);
result = _productService.getProducts();
console.log(result);
